---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: java-alpine-3.6-default
    image: alpine:3.6
  - name: java-alpine-3.6-openjdk-7-jre
    image: alpine:3.6
  - name: java-alpine-3.6-openjdk-8-jre
    image: alpine:3.6
  - name: java-alpine-3.6-openjdk-7-jdk
    image: alpine:3.6
  - name: java-alpine-3.6-openjdk-8-jdk
    image: alpine:3.6
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: alpine-3.6
verifier:
  name: goss
  lint:
    name: yamllint
