---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: java-fedora-27-default
    image: fedora:27
  - name: java-fedora-27-openjdk-8-jre
    image: fedora:27
  - name: java-fedora-27-openjdk-9-jre
    image: fedora:27
  - name: java-fedora-27-openjdk-8-jdk
    image: fedora:27
  - name: java-fedora-27-openjdk-9-jdk
    image: fedora:27
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: fedora-27
verifier:
  name: goss
  lint:
    name: yamllint
