---
#
# Ansible managed
#
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="amazonlinux" tag="1"
    - image="amazonlinux" tag="latest"
    - image="alpine" tag="latest"
    - image="alpine" tag="edge"
    - image="debian" tag="latest"
    - image="debian" tag="testing"
    - image="debian" tag="unstable"
    - image="fedora" tag="30"
    - image="fedora" tag="latest"
    - image="fedora" tag="rawhide"
    - image="centos" tag="7"
    - image="centos" tag="latest"
    - image="opensuse" tag="latest"
    - image="ubuntu" tag="latest"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "MCuv6yhgLBH0MDE5n0SyyUXgipF7b6l6ex54m/aR/AHEbxYs3DHHm2IKAKVLz3xkRtL72TnIAglrvgb7iocE6as64kHP1ahxexvN0Qbt1bGW6HlJ2n2Y4Iv5tXRiC8HyPVx2gOOHbwiRXblsy6ckCOy0DaKpFUnJ+CYzTZs3iDgDhURZgxFzN/Mhy4AoQof9qPaCTuwNfYBBBgSTZCPLQShB3NLcze6O5e1GP07neU3r+YsfHwtN7SkwKxDBX9e60CwQULLh3rHHC5J/axDvGNyNg9SYyJN+cZQffPhhZepGIMoi8G8UjySmRz2wEdcqij2tTICtMpPywQy3DBhnxvHPyuI6LDQ6qYADch/kpwcRoUYBhGK1gTmh/wuwvhstANjc1mPLNsM0ryyDJxPp6aW3ahicAFg4zoV9R96ilD/kh+JsX0885o+wd4ub94qSzSsu4dx3yzNQM/LCbXrVVESKctX4zaDxr8+fKuYC/+rFu2tBz1ElnJf/CsDxy6IbS6XDp5VJhxLBaZl6jBivHHJicl0P42zkgTfCwnFFvHkZEMXJPYP72WncTBrsG8Oj84qfIast84rYz9CA3DbnNZ3UTJVOaSCrsNdoMoJ7pygBGrIOU0Jr/KNCGkj7WoBXNQZ07y/u1t9RHlkCoDc1Xr5pCJCIhHB8FieqZgQyxxY="
  email: false
