---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: java-ubuntu-bionic-default
    image: ubuntu:bionic
  - name: java-ubuntu-bionic-openjdk-8-jre
    image: ubuntu:bionic
  - name: java-ubuntu-bionic-openjdk-11-jre
    image: ubuntu:bionic
  - name: java-ubuntu-bionic-openjdk-8-jdk
    image: ubuntu:bionic
  - name: java-ubuntu-bionic-openjdk-11-jdk
    image: ubuntu:bionic
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: ubuntu-bionic
verifier:
  name: goss
  lint:
    name: yamllint
