---
# tasks file for java
- name: load default variables
  include_vars:
    file: "{{ item }}"
  with_items:
    - default.yml
    - oracle.yml

- name: load os-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - default.yml

- name: install software (package)
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ java_openjdk_package[java_type][java_version]['name'] | default([]) }}"
  when:
    java_vendor == "openjdk"
  register: packageresult
  until: packageresult is succeeded
  retries: 3
  environment:
    USE: "X -cups -alsa -fontconfig"

- name: copy software (rpm)
  copy:
    src: "{{ item }}"
    dest: "/tmp/{{ item }}"
  with_items:
    - "{{ java_oracle_package[java_type][java_version]['rpm'] | default([]) }}"
  when:
    - java_rpm_source == "local"
    - java_format == "rpm"

- name: install software (rpm) (local)
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "/tmp/{{ java_oracle_package[java_type][java_version]['rpm'] | default([]) }}"
  when:
    - java_rpm_source == "local"
    - java_format == "rpm"

- name: install software (rpm) (repository)
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ java_oracle_package[java_type][java_version]['rpm'] | default([]) }}"
  when:
    - java_rpm_source == "repository"
    - java_format == "rpm"

- name: ensure java_install_directory exists
  file:
    path: "{{ java_install_directory }}"
    state: directory
  when:
    - java_vendor == "oracle"
    - java_format == "targz"

- name: install software (targz)
  unarchive:
    src: "{{ java_oracle_package[java_type][java_version]['targz'] | default([]) }}"
    dest: "{{ java_install_directory }}"
  when:
    - java_format == "targz"
    - java_vendor == "oracle"

- name: install policy software (targz)
  unarchive:
    src: jce_policy-8.zip
    dest: "{{ java_install_directory }}"
  when:
    - java_jce
    - java_version == 8
    - java_vendor == "oracle"

- name: set alternative (targz)
  alternatives:
    name: java
    link: /usr/bin/java
    path: "{{ java_install_directory }}/{{ java_oracle_package[java_type][java_version]['directory'] }}/bin/java"
  when:
    - java_format == "targz"
    - ansible_distribution != "Alpine"
    - java_vendor == "oracle"
