---
# tasks file for java
- name: install software (package)
  package:
    name: "{{ item }}"
  with_items:
    - " {{ java_packages['openjdk'][ansible_distribution][java_type][java_version]['name']
      | default(java_package['openjdk'][ansible_distribution][ansible_distribution_major_version][java_type][java_version]['name']
      | default([])) }}"

- name: copy software (rpm)
  copy:
    src: "{{ item }}"
    dest: "/tmp/{{ item }}"
  with_items:
    - "{{ java_package['oracle'][java_type][java_version]['rpm'] | default([]) }}"
  when:
    - java_rpm_source == "local"
    - java_format == "rpm"

- name: install software (rpm) (local)
  package:
    name: "{{ item }}"
  with_items:
    - "/tmp/{{ java_package['oracle'][java_type][java_version]['rpm'] | default([]) }}"
  when:
    - java_rpm_source == "local"
    - java_format == "rpm"

- name: install software (rpm) (repository)
  package:
    name: "{{ item }}"
  with_items:
    - "{{ java_package['oracle'][java_type][java_version]['rpm'] | default([]) }}"
  when:
    - java_rpm_source == "repository"
    - java_format == "rpm"

- name: ensure java_install_directory exists
  file:
    path: "{{ java_install_directory }}"
    state: directory
  when:
    - java_vendor == "oracle"
    - java_format == "targz"

- name: install software (targz)
  unarchive:
    src: "{{ item }}"
    dest: "{{ java_install_directory }}"
  with_items:
    - "{{ java_package['oracle'][java_type][java_version]['targz'] | default([]) }}"
  when:
    - java_format == "targz"
    - java_vendor == "oracle"

- name: install policy software (targz)
  unarchive:
    src: jce_policy-8.zip
    dest: "{{ java_install_directory }}"
  when:
    - java_jce
    - java_version == 8
    - java_vendor == "oracle"

- name: set alternative (targz)
  alternatives:
    name: java
    link: /usr/bin/java
    path: "{{ java_install_directory }}/{{ java_package['oracle'][java_type][java_version]['directory'] }}/bin/java"
  when:
    - java_format == "targz"
    - ansible_distribution != "Alpine"
    - java_vendor == "oracle"
