---
# tasks file for java
- name: install openjdk java (package)
  package:
    name: "{{ java_openjdk_package[java_type][java_version][ansible_distribution]
          | default(java_openjdk_package[java_type][java_version]['default']
          | default([])) }}"
    state: present
  when:
    java_vendor == "openjdk"
  register: packageresult
  until: packageresult is succeeded
  retries: 3
  environment:
    USE: "X -cups -alsa -fontconfig"

- name: copy oracle java (rpm)
  copy:
    src: "{{ item }}"
    dest: "/tmp/{{ item }}"
  with_items:
    - "{{ java_oracle_package[java_type][java_version]['rpm'] | default([]) }}"
  when:
    - java_rpm_source == "local"
    - java_format == "rpm"

- name: install oracle java (rpm) (local)
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "/tmp/{{ java_oracle_package[java_type][java_version]['rpm'] | default([]) }}"
  when:
    - java_rpm_source == "local"
    - java_format == "rpm"

- name: install oracle java (rpm) (repository)
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ java_oracle_package[java_type][java_version]['rpm'] | default([]) }}"
  when:
    - java_rpm_source == "repository"
    - java_format == "rpm"

- name: ensure java_install_directory exists
  file:
    path: "{{ java_install_directory }}"
    state: directory
  when:
    - java_vendor == "oracle"
    - java_format == "targz"

- name: install oracle java (targz)
  unarchive:
    src: "{{ java_oracle_package[java_type][java_version]['targz'] | default([]) }}"
    dest: "{{ java_install_directory }}"
  when:
    - java_format == "targz"
    - java_vendor == "oracle"

- name: install oracle java policy software (targz)
  unarchive:
    src: jce_policy-8.zip
    dest: "{{ java_install_directory }}"
  when:
    - java_jce
    - java_version == 8
    - java_vendor == "oracle"

- name: set alternative (targz)
  alternatives:
    name: java
    link: /usr/bin/java
    path: "{{ java_install_directory }}/{{ java_oracle_package[java_type][java_version]['directory'] }}/bin/java"
  when:
    - java_format == "targz"
    - ansible_distribution != "Alpine"
    - java_vendor == "oracle"
