---
# Oracle JRE
- name: oracle 8 jre
  hosts: "*-oracle-8-jre"
  gather_facts: false
  become: true

  roles:
    - role: robertdebock.bootstrap
    - role: ansible-role-java
      java_vendor: oracle

- name: oracle 9 jre
  hosts: "*-oracle-9-jre"
  gather_facts: false
  become: true

  roles:
    - role: robertdebock.bootstrap
    - role: ansible-role-java
      java_vendor: oracle
      java_version: 9

- name: oracle 10 jre
  hosts: "*-oracle-10-jre"
  gather_facts: false
  become: true

  roles:
    - role: robertdebock.bootstrap
    - role: ansible-role-java
      java_vendor: oracle
      java_version: 10

# Oracle JDK
- name: oracle 8 jdk
  hosts: "*-oracle-8-jdk"
  gather_facts: false
  become: true

  roles:
    - role: robertdebock.bootstrap
    - role: ansible-role-java
      java_vendor: oracle
      java_type: jdk

- name: oracle 9 jdk
  hosts: "*-oracle-9-jdk"
  gather_facts: false
  become: true

  roles:
    - role: robertdebock.bootstrap
    - role: ansible-role-java
      java_vendor: oracle
      java_version: 9
      java_type: jdk

- name: oracle 10 jdk
  hosts: "*-oracle-10-jdk"
  gather_facts: false
  become: true

  roles:
    - role: robertdebock.bootstrap
    - role: ansible-role-java
      java_vendor: oracle
      java_version: 10
      java_type: jdk

# Oracle JRE rpm
- name: oracle 8 jre rpm
  hosts: "*-oracle-8-jre-rpm"
  gather_facts: false
  become: true

  roles:
    - role: robertdebock.bootstrap
    - role: ansible-role-java
      java_vendor: oracle
      java_format: rpm

- name: oracle 9 jre rpm
  hosts: "*-oracle-9-jre-rpm"
  gather_facts: false
  become: true

  roles:
    - role: robertdebock.bootstrap
    - role: ansible-role-java
      java_vendor: oracle
      java_version: 9
      java_format: rpm

- name: oracle 10 jre rpm
  hosts: "*-oracle-10-jre-rpm"
  gather_facts: false
  become: true

  roles:
    - role: robertdebock.bootstrap
    - role: ansible-role-java
      java_vendor: oracle
      java_version: 10
      java_format: rpm

# Oracle JDK rpm
- name: oracle 8 jdk rpm
  hosts: "*-oracle-8-jdk-rpm"
  gather_facts: false
  become: true

  roles:
    - role: robertdebock.bootstrap
    - role: ansible-role-java
      java_vendor: oracle
      java_type: jdk
      java_format: rpm

- name: oracle 9 jdk rpm
  hosts: "*-oracle-9-jdk-rpm"
  gather_facts: false
  become: true

  roles:
    - role: robertdebock.bootstrap
    - role: ansible-role-java
      java_vendor: oracle
      java_version: 9
      java_type: jdk
      java_format: rpm

- name: oracle 10 jdk rpm
  hosts: "*-oracle-10-jdk-rpm"
  gather_facts: false
  become: true

  roles:
    - role: robertdebock.bootstrap
    - role: ansible-role-java
      java_vendor: oracle
      java_version: 10
      java_type: jdk
      java_format: rpm
