---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: java-opensuse-42.2-default
    image: opensuse:42.2
  - name: java-opensuse-42.2-openjdk-7-jre
    image: opensuse:42.2
  - name: java-opensuse-42.2-openjdk-8-jre
    image: opensuse:42.2
  - name: java-opensuse-42.2-openjdk-7-jdk
    image: opensuse:42.2
  - name: java-opensuse-42.2-openjdk-8-jdk
    image: opensuse:42.2
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: opensuse-42.2
verifier:
  name: goss
  lint:
    name: yamllint
