---
- name: install centos 6 openjdk 8
  hosts: centos-6-openjdk-8
  gather_facts: false
  become: true

  roles:
    - role: ansible-role-java
      java_vendor: openjdk
      java_version: 8

- name: install centos 6 oracle 9
  hosts: centos-6-oracle-9
  gather_facts: false
  become: true

  roles:
    - role: ansible-role-java
      java_vendor: oracle
      java_version: 9


- name: install centos 7 openjdk 8
  hosts: centos-7-openjdk-8
  gather_facts: false
  become: true

  roles:
    - role: ansible-role-java
      java_vendor: openjdk
      java_version: 8

- name: install centos 7 oracle 9
  hosts: centos-7-oracle-9
  gather_facts: false
  become: true

  roles:
    - role: ansible-role-java
      java_vendor: oracle
      java_version: 9

- name: install debian 8 openjdk 8
  hosts: debian-8-openjdk-8
  gather_facts: false
  become: true

  roles:
    - role: ansible-role-java
      java_vendor: openjdk
      java_version: 8

- name: install debian 8 oracle 9
  hosts: debian-8-oracle-9
  gather_facts: false
  become: true

  roles:
    - role: ansible-role-java
      java_vendor: oracle
      java_version: 9

- name: install debian buster openjdk 8
  hosts: debian-buster-openjdk-8
  gather_facts: false
  become: true

  roles:
    - role: ansible-role-java
      java_vendor: openjdk
      java_version: 8

- name: install debian buster oracle 9
  hosts: debian-buster-oracle-9
  gather_facts: false
  become: true

  roles:
    - role: ansible-role-java
      java_vendor: oracle
      java_version: 9

- name: install fedora 26 openjdk 9
  hosts: fedora-26-openjdk-9
  gather_facts: false
  become: true

  roles:
    - role: ansible-role-java
      java_vendor: openjdk
      java_version: 9

- name: install fedora 26 oracle 9
  hosts: fedora-26-oracle-9
  gather_facts: false
  become: true

  roles:
    - role: ansible-role-java
      java_vendor: oracle
      java_version: 9

- name: install fedora 27 openjdk 9
  hosts: fedora-27-openjdk-9
  gather_facts: false
  become: true

  roles:
    - role: ansible-role-java
      java_vendor: openjdk
      java_version: 9

- name: install fedora 27 oracle 9
  hosts: fedora-27-oracle-9
  gather_facts: false
  become: true

  roles:
    - role: ansible-role-java
      java_vendor: oracle
      java_version: 9

- name: install ubuntu trusty openjdk 7
  hosts: ubuntu-trusty-openjdk-7
  gather_facts: false
  become: true

  roles:
    - role: ansible-role-java
      java_vendor: openjdk
      java_version: 7

- name: install ubuntu artful oracle 9
  hosts: ubuntu-artful-oracle-9
  gather_facts: false
  become: true

  roles:
    - role: ansible-role-java
      java_vendor: oracle
      java_version: 9
