---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: java-debian-buster-default
    image: debian:buster
  - name: java-debian-buster-openjdk-7-jre
    image: debian:buster
  - name: java-debian-buster-openjdk-8-jre
    image: debian:buster
  - name: java-debian-buster-openjdk-9-jre
    image: debian:buster
  - name: java-debian-buster-openjdk-10-jre
    image: debian:buster
  - name: java-debian-buster-openjdk-11-jre
    image: debian:buster
  - name: java-debian-buster-openjdk-7-jdk
    image: debian:buster
  - name: java-debian-buster-openjdk-8-jdk
    image: debian:buster
  - name: java-debian-buster-openjdk-9-jdk
    image: debian:buster
  - name: java-debian-buster-openjdk-10-jdk
    image: debian:buster
  - name: java-debian-buster-openjdk-11-jdk
    image: debian:buster
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: debian-buster
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - check
    - side_effect
    - verify
    - destroy
verifier:
  name: goss
  lint:
    name: 'flake8'
