---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: java-debian-buster-default
    image: debian:buster
  - name: java-debian-buster-openjdk-8-jre
    image: debian:buster
  - name: java-debian-buster-openjdk-9-jre
    image: debian:buster
  - name: java-debian-buster-openjdk-8-jdk
    image: debian:buster
  - name: java-debian-buster-openjdk-9-jdk
    image: debian:buster
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: debian-buster
verifier:
  name: goss
  lint:
    name: yamllint
