---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: check if connection still works
      ping:

    - name: check if java can be started
      command: java -version
      changed_when: no
