---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: java-debian-stretch-default
    image: debian:stretch
  - name: java-debian-stretch-openjdk-8-jre
    image: debian:stretch
  - name: java-debian-stretch-openjdk-8-jdk
    image: debian:stretch
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: debian-stretch
verifier:
  name: goss
  lint:
    name: yamllint
