---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: java-opensuse-tumbleweed-default
    image: opensuse:tumbleweed
  - name: java-opensuse-tumbleweed-openjdk-7-jre
    image: opensuse:tumbleweed
  - name: java-opensuse-tumbleweed-openjdk-8-jre
    image: opensuse:tumbleweed
  - name: java-opensuse-tumbleweed-openjdk-7-jdk
    image: opensuse:tumbleweed
  - name: java-opensuse-tumbleweed-openjdk-8-jdk
    image: opensuse:tumbleweed
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: opensuse-tumbleweed
verifier:
  name: goss
  lint:
    name: yamllint
