---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: java-centos-7-default
    image: centos:7
  - name: java-centos-7-openjdk-6-jre
    image: centos:7
  - name: java-centos-7-openjdk-7-jre
    image: centos:7
  - name: java-centos-7-openjdk-8-jre
    image: centos:7
  - name: java-centos-7-openjdk-6-jdk
    image: centos:7
  - name: java-centos-7-openjdk-7-jdk
    image: centos:7
  - name: java-centos-7-openjdk-8-jdk
    image: centos:7
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: centos-7
verifier:
  name: goss
  lint:
    name: yamllint
