---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: java-fedora-28-default
    image: fedora:28
  - name: java-fedora-28-openjdk-8-jre
    image: fedora:28
  - name: java-fedora-28-openjdk-9-jre
    image: fedora:28
  - name: java-fedora-28-openjdk-8-jdk
    image: fedora:28
  - name: java-fedora-28-openjdk-9-jdk
    image: fedora:28
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: fedora-28
verifier:
  name: goss
  lint:
    name: yamllint
