---
- name: Converge
  hosts: "*-openjdk-7-jre"
  gather_facts: no

  roles:
    - role: robertdebock.bootstrap
    - role: ansible-role-java
      java_version: 7

- name: Converge
  hosts: "*-openjdk-7-jdk"
  gather_facts: no

  roles:
    - role: robertdebock.bootstrap
    - role: ansible-role-java
      java_version: 7
      java_type: jdk
