---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: java-gentoo-default
    image: gentoo/stage3-amd64
  - name: java-gentoo-openjdk-8-jre
    image: gentoo/stage3-amd64
  - name: java-gentoo-openjdk-8-jdk
    image: gentoo/stage3-amd64
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: gentoo
verifier:
  name: goss
  lint:
    name: yamllint
